{"uuid": "04e36b33-f624-4282-ba71-3c9b3830fdd7", "children": ["06571c43-12d1-466c-91c7-30fb7205b12e"], "befores": [{"name": "click_device_manage", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\wangzhicheng\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\wangzhicheng\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\wangzhicheng\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\IOT\\cloud_printer_project\\auto_test\\gitlab_test\\cloud-printer\\TestCases\\conftest.py\", line 72, in click_device_manage\n    login_success[3].click_IOT_device_manage()\n  File \"E:\\IOT\\cloud_printer_project\\auto_test\\gitlab_test\\cloud-printer\\PageObjects\\home_page_objects.py\", line 20, in click_IOT_device_manage\n    self.click_element(loc.iot_device_manage,module='主界面-点击IOT设备管理')\n  File \"E:\\IOT\\cloud_printer_project\\auto_test\\gitlab_test\\cloud-printer\\Common\\base_page_object.py\", line 138, in click_element\n    self.wait_element_visible(loc, module, timeout, poll_frequency)\n  File \"E:\\IOT\\cloud_printer_project\\auto_test\\gitlab_test\\cloud-printer\\Common\\base_page_object.py\", line 55, in wait_element_visible\n    WebDriverWait(self.driver, timeout, poll_frequency).until(EC.visibility_of_element_located(loc))\n  File \"C:\\Users\\wangzhicheng\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1600419119382, "stop": 1600419140047}], "start": 1600419119382, "stop": 1600419140464}